import "./globals.css";
import Navbar from "./components/Navbar";
import Mobile_sidebar from "./components/Mobile_sidebar";
import ReduxProvider from "./redux-store/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <ReduxProvider>
          <Navbar />
          <Mobile_sidebar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
